# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ethical-sale-app"
client_id = "12bb8918fd32c9ffebb9425b8bb15eff"
application_url = "https://crew-penny-utilize-along.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://crew-penny-utilize-along.trycloudflare.com/auth/callback",
  "https://crew-penny-utilize-along.trycloudflare.com/auth/shopify/callback",
  "https://crew-penny-utilize-along.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-store-2023-23.myshopify.com"
